Performing system checks...

System check identified no issues (0 silenced).

You have 14 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
July 31, 2018 - 23:31:00
Django version 2.0.7, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CTRL-BREAK.
Not Found: /
[31/Jul/2018 23:31:08] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:33:18] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:33:19] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:33:19] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:33:19] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:33:19] "GET / HTTP/1.1" 404 2053
Performing system checks...

System check identified no issues (0 silenced).

You have 14 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
July 31, 2018 - 23:33:09
Django version 2.0.7, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).

You have 14 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
July 31, 2018 - 23:34:55
Django version 2.0.7, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).

You have 14 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
July 31, 2018 - 23:42:17
Django version 2.0.7, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).

You have 14 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
July 31, 2018 - 23:42:52
Django version 2.0.7, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CTRL-BREAK.
Not Found: /
[31/Jul/2018 23:42:56] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:42:57] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:42:57] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:42:57] "GET / HTTP/1.1" 404 2053
Performing system checks...

System check identified no issues (0 silenced).

You have 14 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
July 31, 2018 - 23:44:11
Django version 2.0.7, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CTRL-BREAK.
Not Found: /
[31/Jul/2018 23:44:13] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:44:23] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:44:37] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:44:38] "GET / HTTP/1.1" 404 2053
Not Found: /
[31/Jul/2018 23:44:38] "GET / HTTP/1.1" 404 2053
Performing system checks...

System check identified no issues (0 silenced).

You have 14 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
July 31, 2018 - 23:44:34
Django version 2.0.7, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).

You have 14 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
August 04, 2018 - 13:21:49
Django version 2.0.7, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CTRL-BREAK.
Not Found: /
[04/Aug/2018 13:22:10] "GET / HTTP/1.1" 404 2053
Not Found: /favicon.ico
[04/Aug/2018 13:22:10] "GET /favicon.ico HTTP/1.1" 404 2104
Not Found: /
[04/Aug/2018 13:22:57] "GET / HTTP/1.1" 404 2053
Not Found: /
[04/Aug/2018 13:22:59] "GET / HTTP/1.1" 404 2053
Not Found: /
[04/Aug/2018 13:23:00] "GET / HTTP/1.1" 404 2053
Performing system checks...

System check identified no issues (0 silenced).

You have 14 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
August 04, 2018 - 13:22:57
Django version 2.0.7, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CTRL-BREAK.
Not Found: /
[13/Aug/2018 00:43:10] "GET / HTTP/1.1" 404 2053
Not Found: /favicon.ico
[13/Aug/2018 00:43:11] "GET /favicon.ico HTTP/1.1" 404 2104
Not Found: /
[13/Aug/2018 15:39:06] "GET / HTTP/1.1" 404 2053
Not Found: /favicon.ico
[13/Aug/2018 15:39:07] "GET /favicon.ico HTTP/1.1" 404 2104
Not Found: /automationserver/
[13/Aug/2018 15:39:21] "GET /automationserver/ HTTP/1.1" 404 3079
[13/Aug/2018 15:40:24] "POST /automationserver/runcase HTTP/1.1" 200 74
* daemon not running; starting now at tcp:5037
* daemon started successfully
[13/Aug/2018 15:44:26] "POST /automationserver/runcase HTTP/1.1" 200 222
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
August 13, 2018 - 15:34:49
Django version 2.1, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CONTROL-C.
未获取到任何设备,不执行自动化程序
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
August 13, 2018 - 15:49:10
Django version 2.1, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
August 13, 2018 - 15:51:05
Django version 2.1, using settings 'automationframework.settings'
Starting development server at http://0.0.0.0:8988/
Quit the server with CONTROL-C.
[13/Aug/2018 15:52:54] "POST /automationserver/runcase HTTP/1.1" 200 222
[13/Aug/2018 15:53:00] "POST /automationserver/runcase HTTP/1.1" 200 222
[13/Aug/2018 16:02:11] "POST /automationserver/runcase HTTP/1.1" 200 222
[13/Aug/2018 16:02:37] "POST /automationserver/runcase HTTP/1.1" 200 222
[13/Aug/2018 16:02:37] "POST /automationserver/runcase HTTP/1.1" 200 222
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1024ce1e0>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Volumes/Software/Personal/Git_Project/Pycharm_Project/automationframework/automationframework/automationframework/urls.py", line 22, in <module>
    url(r'^automationserver/', include('automationserver.urls'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Volumes/Software/Personal/Git_Project/Pycharm_Project/automationframework/automationframework/automationserver/urls.py", line 3, in <module>
    from automationserver import views
  File "/Volumes/Software/Personal/Git_Project/Pycharm_Project/automationframework/automationframework/automationserver/views.py", line 5, in <module>
    from automationserver import data_read, new_thread_automation, run_web_automation, run_interface_automation
  File "/Volumes/Software/Personal/Git_Project/Pycharm_Project/automationframework/automationframework/automationserver/new_thread_automation.py", line 5, in <module>
    from automationserver import run_app_automation, data_read, send_report  # 启动django服务需要开启
  File "/Volumes/Software/Personal/Git_Project/Pycharm_Project/automationframework/automationframework/automationserver/run_app_automation.py", line 79
    Django 服务开启
              ^
SyntaxError: invalid syntax
